services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend    
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    networks:
      - backend
  db:
    image: postgres:11
    container_name: bop_tool_postgres
    ports:
      - "65432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: bop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    hostname: postgres
    restart: always
    user: root
    stdin_open: true
networks:
  frontend:
  backend:
